name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Installing NPM packages
        run: npm install

      - name: Building project
        run: npm run build

      # - name: Running tests
        # run: npm run test

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: page
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: page
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main